//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0

use super::sea_orm_active_enums::MyEnum;
use sea_orm::entity::prelude::*;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = \"table\")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub payload : MyEnum , pub payload_binary : MyEnum , } # [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { } impl ActiveModelBehavior for ActiveModel { }