//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

pub type FruitId = sea_orm::Id<Entity, i32>;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fruit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: FruitId,
    pub name: String,
    pub cake_id: Option<super::cake::CakeId>,
    #[sea_orm(belongs_to, from = "cake_id", to = "id")]
    pub cake: HasOne<super::cake::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
