//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(try_from_u64)]
pub struct UserFollowerPkUserId(pub super::user::UserId);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(try_from_u64)]
pub struct UserFollowerPkFollowerId(pub super::user::UserId);

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_follower")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: UserFollowerPkUserId,
    #[sea_orm(primary_key, auto_increment = false)]
    pub follower_id: UserFollowerPkFollowerId,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::FollowerId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl ActiveModelBehavior for ActiveModel {}
