//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

pub type UserId = sea_orm::Id<Entity, i64>;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment)]
    pub id: UserId,
    #[sea_orm(unique)]
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::member::Entity")]
    Member,
    #[sea_orm(has_many = "super::reaction::Entity")]
    Reaction,
}

impl Related<super::member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Member.def()
    }
}

impl Related<super::reaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reaction.def()
    }
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        super::member::Relation::Guild.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
